### model
model_name_or_path: /mnt/disk1/qinqian/hf_home/hub/models--Qwen--Qwen2.5-VL-7B-Instruct/snapshots/5b5eecc7efc2c3e86839993f2689bbbdf06bd8d4
image_max_pixels: 400000
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: Canon1DsMkIII_direction_16bit_v2_train  # 使用你的自定义数据集
dataset_dir: data
media_dir: /mnt/disk3/shuwei/NUS-8/sRGB_16bit_data_v2/Canon1DsMkIII  # 图片文件所在目录
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 8

### output
output_dir: saves/1001-Canon1DsMkIII_direction_16bit_sRGB_v2_lr_4e_4_512samples_epochs_8_fp32_projector_vision/lora/sft
logging_steps: 10
save_steps: 100  # 由于数据集较小，减少保存步数
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 16
learning_rate: 4.0e-4
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false  # 使用fp32保持16bit图像的完整精度
ddp_timeout: 180000000
resume_from_checkpoint: null

freeze_multi_modal_projector: false
freeze_vision_tower: false

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 50  # 由于数据集较小，减少评估步数 