### export OMP_NUM_THREADS=32
# export CUDA_VISIBLE_DEVICES=7
# InternVL3.5-1B-hf 模型
model_name_or_path: /mnt/disk3/shuwei/models-checkpoint/models--OpenGVLab--InternVL3_5-1B-HF/snapshots/9191dbccf312b537016f041b25d61c72e7c5c9f3
image_max_pixels: 400000
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset NUS8_v2 (old), gehler_v2 (old), inter-tau_v1 (old), cube+_v1
dataset: NUS8_v2, inter-tau_v1, cube+_v1
dataset_dir: data
# media_dir: 
template: intern_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 8

### output_direction_16bit_v2, 
output_dir: saves/2026-01-26-internvl3.5-1b-cross_direction_16bit_sRGB_lr_4e_4_512samples_epochs_8_fp32_multi-sensor/lora/sft
logging_steps: 10
save_steps: 20  # 由于数据集较小，减少保存步数
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train 64*8 
per_device_train_batch_size: 100  # 1B模型显存占用更小，可以增大batch size
gradient_accumulation_steps: 8  # 保持相同的有效batch size (64*8 = 512)
learning_rate: 4.0e-4
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false  # 使用fp32保持16bit图像的完整精度
ddp_timeout: 180000000
resume_from_checkpoint: null
## null
freeze_multi_modal_projector: false
freeze_vision_tower: false
freeze_language_model: false

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 50  # 由于数据集较小，减少评估步数 